"""Generate a self-contained vector TV banner; requires fonttools and NotoSansSC-Medium.otf.

Font source: https://github.com/notofonts/noto-cjk/tree/main/Sans/SubsetOTF/SC
Only four glyph outlines are packaged, never the font file. See third_party/NotoSansCJK.LICENSE.
Usage: python scripts/build-tv-banner.py path/to/NotoSansSC-Medium.otf
"""
import copy
import sys
from pathlib import Path
import xml.etree.ElementTree as ET

from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen

ROOT = Path(__file__).resolve().parents[1]
NS = "http://schemas.android.com/apk/res/android"
ET.register_namespace("android", NS)


def attrs(**values):
    return {f"{{{NS}}}{key}": str(value) for key, value in values.items()}


def main(font_path):
    vector = ET.Element("vector", attrs(width="160dp", height="90dp",
                                        viewportWidth=320, viewportHeight=180))
    # Some launchers do not retain the background of a layered banner drawable.
    # Make the full-bleed opaque background part of the same vector as the mark.
    ET.SubElement(vector, "path", attrs(fillColor="#246FDC", pathData="M0,0 H320 V180 H0 Z"))
    source = ET.parse(ROOT / "scripts/artwork/ic_launcher_foreground.xml")
    mark = copy.deepcopy(source.getroot().find("group"))
    mark.attrib = attrs(scaleX=0.45, scaleY=0.45, translateX=19, translateY=31)
    vector.append(mark)
    with TTFont(font_path) as font:
        glyphs, cmap = font.getGlyphSet(), font.getBestCmap()
        scale = 36 / font["head"].unitsPerEm
        for index, char in enumerate("网页电视"):
            pen = SVGPathPen(glyphs, ntos=lambda value: f"{value:.3f}".rstrip("0").rstrip("."))
            glyphs[cmap[ord(char)]].draw(TransformPen(pen, (scale, 0, 0, -scale, 140 + index * 36, 104)))
            ET.SubElement(vector, "path", attrs(fillColor="#FFFFFFFF", pathData=pen.getCommands()))
    target = ROOT / "app/src/main/res/drawable-anydpi-v21/tv_banner.xml"
    target.parent.mkdir(parents=True, exist_ok=True)
    ET.indent(vector, space="    ")
    target.write_text('<?xml version="1.0" encoding="utf-8"?>\n'
                      '<!-- Generated by scripts/build-tv-banner.py; Noto Sans SC glyph outlines. -->\n'
                      + ET.tostring(vector, encoding="unicode") + '\n', encoding="utf-8")
    print(target, target.stat().st_size, "bytes")


if __name__ == "__main__":
    main(sys.argv[1])
